import type { Metadata } from "next";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";

export const metadata: Metadata = {
  title: "Página principal",
  description: "Generated by create next app",
};

export const viewport = {
  width:1920,
  height:1080,
  initialSacale: 1.0,
  maximumScale:5.0,
  colorScheme:'dark'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/> 
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
