import { Metadata } from "next";
import Cabecalho from "./components/cabecalho/cabecalho";
import Rodape from "./components/Rodape/Rodape";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewPort = {
  initialScale: 1.0,
  width: "device-width", 
  colorScheme: "dark"
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Rodape />
      </body>
    </html>
  );
}
